
export const TEACHERS_MAP = new Map<string, string>([
    ["AtMa", "Marie-Liesse  ATTELEYN"],
    ["BaMa", "Maxime BAUMANN"],
    ["BaPh", "Philippe BAUCHEREL"],
    ["BiCh", "Chantal BIELAWSKI"],
    ["BlPa", "Patrick BLONDELLE"],
    ["BoKa", "Karin BOELEN"],
    ["BoPa", "Pascal BOURDÉ"],
    ["BrEr", "Eric BRASSART"],
    ["CaAl", "Alexandre CARPENTIER"],
    ["CGI", "CGI ENTREPRISE"],
    ["ClAr", "Arnaud CLÉRENTIN"],
    ["CoOl", "Olivia CONFLANT"],
    ["DeEm", "Emma DEBAR"],
    ["DeLa", "Laurent DELAHOCHE"],
    ["DeNi", "Nicolas DELPECH"],
    ["DiCh", "Charlotte DIMPRE"],
    ["DjAr", "Arseme Djeufack NANFACK"],
    ["DuDa", "David DURAND"],
    ["ErYo", "Yoan EROSTAN"],
    ["FaSy", "Sylvie FARES"],
    ["GeJe", "Jérome GÉRARD"],
    ["HeLa", "Laurent HERJEAN"],
    ["HoFr", "Frédérique HOREN"],
    ["HuXa", "Xavier HUBIN"],
    ["JaFr", "Frédéric JANURA"],
    ["KaMe", "Mélanie KAZUMBA"],
    ["KaOm", "Omar KABBAJ"],
    ["KeBr", "Brigitte KERVELLA"],
    ["KrDa", "David KRIZAN"],
    ["LaJe", "Jerry Lacmou ZEUTOUO"],
    ["LaJu", "Julian LAYEN"],
    ["LaTh", "Thomas LANGLET"],
    ["LeCl", "Clément LECAT"],
    ["LeQu", "Quentin LECLET"],
    ["LeSa", "Sandrine LELIÈVRE"],
    ["LeVa", "Valentin Le BASTARD"],
    ["LeXa", "Xavier LELIÈVRE"],
    ["LoCh", "Christophe LOGÉ"],
    ["LoFr", "François LOUARN"],
    ["LoYa", "Yann LOUARN"],
    ["LuCo", "Corinne LUCET"],
    ["MaAm", "Amine MANIAR"],
    ["MaBr", "Bruno MARHIC"],
    ["MaJe", "JeanBaptiste  MASSON"],
    ["MaTo", "Tony MARÉ"],
    ["MeSy", "Sylvain MERCIER"],
    ["MoEl", "El Mustapha  MOUADDIB"],
    ["PeJo", "Jocelyn PÉCOURT"],
    ["PeKe", "Kévin PÉCRO"],
    ["PeLo", "Louis PÉAN"],
    ["PeMi", "Michel PETREMANN"],
    ["PeRe", "Renaud PERRAI"],
    ["PeSa", "Samuel PETITE"],
    ["PlAr", "Arthur PLASKOWSKI"],
    ["RoBa", "Bastien ROUSSEL"],
    ["RoEr", "Eric RODRIGUEZ"],
    ["SeSa", "Samuel SENECA"],
    ["ThMa", "Marie-Catherine  THIÉTARD"],
    ["ThQu", "Quentin THÉRY"],
    ["ThVi", "Vincent THIBAUT"],
    ["VaPa", "Pascal VASSEUR"],
    ["WaTh", "Thomas WARO"],
]);

export const AMPHIS_MAP = new Map<string, string>([
    ["GMP", "Lambert"],
    ["NA", "Nouvel amphi"],
    ["GB", "Génie Biologique"],
    ["BC", "Bloc central"],
]);
