
export const TEACHERS_MAP = new Map<string, string>([
    ["LoCh", "Christophe LOGÉ"],
    ["CoOl", "Olivia CONFLANS"],
    ["MaBr", "Bruno MAHRIC"],
    ["LaTh", "Thomas LANGLET"],
    ["DuDa", "David DURAND"],
    ["BiCh", "Chantal BIELAWSKI"],
    ["BaMa", "Maxime BAUMANN"],
    ["PeKe", "Kévin PÉCRO"],
    ["HeLa", "Laurent HERJEAN"],
    ["MaJe", "Jean-Baptiste MASSON"],
    ["BoPa", "Pascal BOURDE"],
    ["JaFr", "Frédéric JANURA"],
    ["PlAr", "Arthur PLASKOWSKI"],
    ["CaAl", "Alexandre CARPENTIER"],
    ["BrEr", "Éric BRASSARD"],
    ["HoFr", "Frédérique HOREN"],
    ["KeBr", "Brigitte KERVELLA"],
    ["DiCh", "Charlotte DIMPRE"],
    ["DeEm", "Emma DEBAR"],
    ["AtMa", "Marie-Liesse ATTELYN"],
    ["FaSy", "Sylvie FARES"],
]);